name: traQraft
version: ${version}
main: jp.trap.traQraft.TraQraft
api-version: ${apiVersion}
author: ${author}
description: ${description}
website: ${website}
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}
